# Generated by Django 3.2.5 on 2021-07-29 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient', models.CharField(max_length=50)),
                ('quantity', models.FloatField()),
                ('unit_of_measure', models.CharField(choices=[('L', 'Liter'), ('Kg', 'Kilograms'), ('g', 'Grams'), ('U', 'Unit')], max_length=20)),
                ('cost', models.FloatField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
