# Generated by Django 3.2.5 on 2021-08-06 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredient',
            options={'get_latest_by': 'created', 'ordering': ['-created', '-modified']},
        ),
        migrations.RenameField(
            model_name='ingredient',
            old_name='ingredient_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='slug_name',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='modified',
            field=models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='modified at'),
        ),
    ]
