# Generated by Django 3.2.5 on 2021-08-06 21:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0002_auto_20210806_2130'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stock',
            options={'get_latest_by': 'created', 'ordering': ['-created', '-modified']},
        ),
        migrations.RemoveField(
            model_name='stock',
            name='ingredient_name',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='quantity_buyed',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='total_cost',
        ),
        migrations.AddField(
            model_name='stock',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Date time on which the object was created.', verbose_name='created at'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stock',
            name='ingredient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='ingredients.ingredient'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stock',
            name='modified',
            field=models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='modified at'),
        ),
        migrations.AddField(
            model_name='stock',
            name='price_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='stock',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
