# Generated by Django 3.2.5 on 2021-08-02 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0002_auto_20210730_2253'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='quantity',
            new_name='quantity_buyed',
        ),
    ]
