# Generated by Django 3.2.5 on 2021-08-06 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0003_rename_quantity_stock_quantity_buyed'),
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe_ingredient',
            name='ingredient_name',
        ),
        migrations.AddField(
            model_name='recipe_ingredient',
            name='ingredient_name',
            field=models.ManyToManyField(related_name='ingredients', to='ingredients.Ingredient'),
        ),
    ]
