# Generated by Django 3.2.5 on 2021-08-06 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0001_initial'),
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe_ingredient',
            name='ingredient_name',
            field=models.ManyToManyField(related_name='ingredients', to='ingredients.Ingredient'),
        ),
        migrations.DeleteModel(
            name='Ingredient',
        ),
        migrations.DeleteModel(
            name='IngredientUnit',
        ),
    ]
